spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore_db #your database url and database name
    username: postgres # set your username
    password: postgres  # set your password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
